### ISSUE TITLE
[BUG] Python version incompatibility with 3.10+

### ISSUE THREAD

**Issue by gsidebo** [akamai/httpie-edgegrid#37]
**Describe the bug**
When installing the package via standard install command, this error comes up
`ImportError: cannot import name 'Mapping' from 'collections' (/home/gsidebot/.pyenv/versions/3.10.4/lib/python3.10/collections/__init__.py)`

Python version I was using is 3.10.4. When I change to 3.9.15 it works.

**To Reproduce**
1. Install the package (`python setup.py install`) with a Python version >= 3.10

**Expected behavior**
Successful install

**Please complete the following information:**
 - OS: Debian Linux running on WSL

**Additional context**
Either the required Python version needs to be updated to limit to <3.10, or the 3.9-incompatible code needs to be fixed, including this `collections` import.

Example SO thread for context (one of many): https://stackoverflow.com/questions/72167725/python-importerror-cannot-import-name-mapping-from-collections-c-progra

**Comment by wzagrajcz** [comment]
Hello @gsidebo 

Thank You for opening the issue. We have some problems in recreating it. When working on virtual environment on Python 3.10.4, running 
```
pip install -r requirements.txt
python setup.py install
```
does not throw any error. Can You please verify if the error still occurs when having run the `pip install -r requirements.txt` before the actual instal?

Best regards,
Wojciech
